# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-267572-kuoth-VivoBook/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tcsg324-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -define ARTY=true {
      /tools/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /tools/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /tools/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -define ARTY=true {
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ip_top/mig_7series_v4_2_memc_ui_top_std.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ip_top/mig_7series_v4_2_mem_intfc.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_top.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_rd_data.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_cmd.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_wr_data.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal_hr.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_tempmon.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_cc.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrcal.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_prbs_gen.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_calib_top.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy_wrapper.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_top.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_4lanes.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_prbs_rdlvl.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_tap_base.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_skip_calib_tap.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_data.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_top.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_cntlr.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl_off_delay.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_init.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_samp.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_if_post_fifo.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_po_cntlr.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_lane.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_mux.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_edge.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_lim.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_oclkdelay_cal.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_of_pre_fifo.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_group_io.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_edge_store.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_meta.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_rdlvl.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ck_addr_cmd_delay.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_pd.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_col_mach.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_cntrl.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_queue.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_cntrl.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_mach.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_select.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_round_robin_arb.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_state.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_mux.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_compare.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_row_col.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_mc.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_common.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_common.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_mach.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_infrastructure.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_iodelay_ctrl.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_clk_ibuf.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_tempmon.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_fi_xor.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_dec_fix.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_merge_enc.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_gen.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_buf.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/mig_7series_0.v
      /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/mig_7series_0_mig.v
    }
      rt::read_vhdl -lib xpm /tools/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top mig_7series_0
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-267572-kuoth-VivoBook/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
