# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
# IP: The module: 'floating_point_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/floating_point_0/floating_point_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
# IP: The module: 'floating_point_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kuoth/school/mp/hw5/hw5_111550105/aquila_mpd/aquila_mpd.gen/sources_1/ip/floating_point_0/floating_point_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
